language: go
go:
- 1.13.x
cache:
  directories:
  - "$GOPATH/pkg/mod"
stages:
- test
- deploy
jobs:
  include:
   if: type = pull_request 
  - stage: test
    script:
    - go test ./... -coverprofile=coverage.out -covermode=atomic
      -p=1
    after_success:
    - bash <(curl -s https://codecov.io/bash)
  if: (type = push AND (branch = master))
  - stage: deploy  
    services:
      - docker
    before_install:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -f Dockerfile -t testorg14/test-http:1.0.0 .
      - docker images
      - docker push testorg14/test-http:1.0.0 
    after_success:
    - bash <(curl -s https://codecov.io/bash)   
