language: go
go:
- 1.14.x
cache:
  directories:
  - "$GOPATH/pkg/mod"
stages:
- test
- name: deploy
  if: (type = push AND (branch = master))
jobs:
  include:
  - stage: test
    script:
    - go test ./... -coverprofile=coverage.out -covermode=atomic
      -p=1
    after_success:
    - bash <(curl -s https://codecov.io/bash)
  - stage: deploy
    on:
      tags: true
    services:
      - docker
    env:
    - TRAVIS_TAG=`echo "$TRAVIS_TAG"`
    before_install:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -f Dockerfile -t testorg14/test-http:$TRAVIS_TAG .
      - docker images
      - docker push testorg14/test-http:$TRAVIS_TAG
