language: go
go:
- 1.13.x
cache:
  directories:
  - "$GOPATH/pkg/mod"
services:
  - docker
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -f Dockerfile -t noritestmember/test-http:1.0.0 .
  - docker images
  - docker tag test-http noritestmember/test-http:1.0.0
  - docker commit test-http noritestmember/test-http:1.0.0
  - docker push noritestmember/test-http:1.0.0 
stages:
- test
jobs:
  include:
  - stage: test
    script:
    - go test ./... -coverprofile=coverage.out -covermode=atomic
      -p=1
    after_success:
    - bash <(curl -s https://codecov.io/bash)
