language: go
go:
- 1.13.x
cache:
  directories:
  - "$GOPATH/pkg/mod"
services:
  - docker
before_install:
  - docker build -f Dockerfile -t test1 .
  - docker run  -p 127.0.0.1:8080:8080 test1
  - docker stop test1
stages:
- test
jobs:
  include:
  - stage: test
    script:
    - go test ./... -coverprofile=coverage.out -covermode=atomic
      -p=1
    after_success:
    - bash <(curl -s https://codecov.io/bash)
